### PR TITLE
Intro outro markers skin settings

### PR DESCRIPTION
**Pull request by Be-ing**
follow up from https://github.com/ninomp/mixxx/pull/1

### CODE REVIEW

**Comment by ninomp** [comment]
Is this also done? Can I merge this PR as well?

**Comment by Be-ing** [comment]
Yes, please merge this.

**Comment by Be-ing** [comment]
You can close #1 because those commits are included here.

**Comment by ninomp** [comment]
Thank you @ronso0 and @Be-ing for your help!

**Pull request merged**
