### PR TITLE
Intro outro markers

### PR DESCRIPTION
**Pull request by ronso0**
- functional in all skins (not styled in Shade, just randomized hotcue icons)
- squeezed buttons at min.size only in Deere
- only one marker per range in (unified) deck overviews

all skins (except Shade) have special button templates. they are configured with `label` and `cue_type`.
for now they use unicode characters to create the icon as that's the only thing we can use in the overviews right now > https://bugs.launchpad.net/mixxx/+bug/1496952

### CODE REVIEW

**Comment by Be-ing** [comment]
Thank you, this looks good. My only suggestion is to rename the skin settings menu items to "Intro/Outro Cues" instead of "AutoDJ Cue Buttons" (and rename the skin CO used for the toggle accordingly).

**Comment by ronso0** [comment]
> Thank you, this looks good. My only suggestion is to rename the skin settings menu items to "Intro/Outro Cues" instead of "AutoDJ Cue Buttons" (and rename the skin CO used for the toggle accordingly).

feel free to edit the settings and CO.
I'll be now travelling for a few weeks. I'll check in now & then and help with comments and small edits though.

**Comment by ronso0** [comment]
..and someone needs to take of the Shade icons.

**Comment by Be-ing** [comment]
done: https://github.com/ninomp/mixxx/pull/2

**Comment by ninomp** [comment]
Is this done? Can I merge this?

**Pull request merged**
